CREATE TABLE [dbo].[Cart]
(
	[CartId] INT NOT NULL IDENTITY PRIMARY KEY,
	[foodName] NVARCHAR(255) NULL FOREIGN KEY REFERENCES FoodItems(foodName) ON DELETE CASCADE,
	[ComboName] NVARCHAR(255) NULL FOREIGN KEY REFERENCES Combo(ComboName) ON DELETE CASCADE,
	[price] DECIMAL(10, 2) NULL
)
