CREATE TABLE [dbo].[Checkout]
(
	[OrderId] INT NOT NULL PRIMARY KEY IDENTITY,
	[CartId] INT NOT NULL FOREIGN KEY REFERENCES Cart(CartId),
	[username] NVARCHAR(50) NOT NULL FOREIGN KEY REFERENCES Customer(username),
	[isCoupons] BIT NULL DEFAULT 0,
	[CouponId] INT FOREIGN KEY REFERENCES Coupons(CouponId),
	[DiscountAmount] DECIMAL (3, 2) NULL,
	[TotalAmount] DECIMAL(10, 2) NOT NULL,
	[Address] NVARCHAR(MAX) NOT NULL,
	[OrderedOn] DATETIME2(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
