CREATE TABLE [dbo].[Customer]
(
	[Id] INT NOT NULL IDENTITY,
	[firstname] NVARCHAR(MAX) NOT NULL,
	[lastname] NVARCHAR(MAX) NOT NULL,
	[email] NVARCHAR(MAX) NOT NULL,
	[username] NVARCHAR(50) NOT NULL PRIMARY KEY,
	[password] NVARCHAR(20) NOT NULL,
	[Membership] BIT NOT NULL DEFAULT 0,
	[dateOfRegistered] DATETIME2(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
